// client/src/presentation/pages/DocumentEditorPage.tsx
import { useState, useEffect, useMemo, useRef, DragEvent } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import 'katex/dist/katex.min.css';
import type { Document, Profile } from '../../../../shared/src/types';
import { documentApi, profileApi } from '../../infrastructure/api';
import { renderDocument } from '../../application/services/documentRenderer';
import { DocumentPreview } from '../components/DocumentPreview';

export function DocumentEditorPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const [document, setDocument] = useState<Document | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [profiles, setProfiles] = useState<Profile[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [isDragging, setIsDragging] = useState(false);

  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (id) {
      loadData(id);
    }
  }, [id]);

  async function loadData(docId: string) {
    try {
      const [docData, profilesData] = await Promise.all([
        documentApi.getById(docId),
        profileApi.getAll(),
      ]);

      setDocument(docData);
      setProfiles(profilesData);

      if (docData.profileId) {
        const p = profilesData.find((x) => x.id === docData.profileId);
        if (p) setProfile(p);
      }
    } catch (error) {
      console.error('Failed to load:', error);
    } finally {
      setLoading(false);
    }
  }

  async function handleSave() {
    if (!document || !id) return;

    setSaving(true);
    try {
      await documentApi.update(id, {
        name: document.name,
        content: document.content,
        profileId: document.profileId,
      });
    } catch (error) {
      console.error('Save failed:', error);
    } finally {
      setSaving(false);
    }
  }

  function handleNameChange(name: string) {
    if (!document) return;
    setDocument({ ...document, name });
  }

  async function handleGeneratePdf() {
    if (!id || !document) return;

    setGenerating(true);
    try {
      // Save first
      await documentApi.update(id, {
        name: document.name,
        content: document.content,
        profileId: document.profileId,
      });

      // Small delay to ensure file is written
      await new Promise((resolve) => setTimeout(resolve, 100));

      const blob = await documentApi.generatePdf(id);
      const url = URL.createObjectURL(blob);
      const a = window.document.createElement('a');
      a.href = url;
      a.download = `${document.name}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('PDF generation failed:', error);
      alert('Ошибка генерации PDF');
    } finally {
      setGenerating(false);
    }
  }

  function handleContentChange(content: string) {
    if (!document) return;
    setDocument({ ...document, content });
  }

  function handleProfileChange(profileId: string) {
    if (!document) return;
    const newProfile = profiles.find((p) => p.id === profileId) || null;
    setProfile(newProfile);
    setDocument({ ...document, profileId });
  }

  async function handleImageUpload(file: File) {
    if (!id || !document) return;

    setUploading(true);
    try {
      const result = await documentApi.uploadImage(id, file);
      const imageMarkdown = `\n![${file.name}](${result.url})\n`;

      const textarea = textareaRef.current;
      if (textarea) {
        const start = textarea.selectionStart;
        const newContent =
          document.content.substring(0, start) +
          imageMarkdown +
          document.content.substring(textarea.selectionEnd);

        setDocument({ ...document, content: newContent });

        setTimeout(() => {
          textarea.selectionStart = textarea.selectionEnd = start + imageMarkdown.length;
          textarea.focus();
        }, 0);
      } else {
        setDocument({ ...document, content: document.content + imageMarkdown });
      }
    } catch (error) {
      console.error('Upload failed:', error);
      alert('Ошибка загрузки изображения');
    } finally {
      setUploading(false);
    }
  }

  function handleDragOver(e: DragEvent<HTMLTextAreaElement>) {
    e.preventDefault();
    setIsDragging(true);
  }

  function handleDragLeave(e: DragEvent<HTMLTextAreaElement>) {
    e.preventDefault();
    setIsDragging(false);
  }

  function handleDrop(e: DragEvent<HTMLTextAreaElement>) {
    e.preventDefault();
    setIsDragging(false);

    const files = e.dataTransfer.files;
    if (files.length > 0 && files[0].type.startsWith('image/')) {
      handleImageUpload(files[0]);
    }
  }

  function handlePaste(e: React.ClipboardEvent<HTMLTextAreaElement>) {
    const items = e.clipboardData.items;
    for (let i = 0; i < items.length; i++) {
      if (items[i].type.startsWith('image/')) {
        e.preventDefault();
        const file = items[i].getAsFile();
        if (file) handleImageUpload(file);
        break;
      }
    }
  }

  const renderedHtml = useMemo(() => {
    if (!document) return '';

    return renderDocument({
      markdown: document.content,
      profile,
      overrides: document.overrides || {},
      selectable: false,
    });
  }, [document?.content, document?.overrides, profile]);

  if (loading) {
    return (
      <div className="page flex items-center justify-center">
        <div className="text-muted">Загрузка...</div>
      </div>
    );
  }

  if (!document) {
    return (
      <div className="page flex items-center justify-center">
        <div className="text-muted">Документ не найден</div>
      </div>
    );
  }

  return (
    <div style={{ height: '100vh', display: 'flex', flexDirection: 'column' }}>
      {/* Toolbar */}
      <div className="toolbar">
        <div className="toolbar-group">
          <button className="btn btn-ghost btn-sm" onClick={() => navigate('/')}>
            ← Назад
          </button>
          <span style={{ color: 'var(--text-muted)' }}>|</span>
          <input
            type="text"
            value={document.name}
            onChange={(e) => handleNameChange(e.target.value)}
            className="form-input"
            style={{
              width: '200px',
              padding: '0.25rem 0.5rem',
              fontSize: '1rem',
              fontWeight: 600,
              background: 'transparent',
              border: '1px solid transparent',
              borderRadius: 'var(--radius-sm)',
            }}
            onFocus={(e) => {
              e.target.style.background = 'var(--bg-tertiary)';
              e.target.style.borderColor = 'var(--border-color)';
            }}
            onBlur={(e) => {
              e.target.style.background = 'transparent';
              e.target.style.borderColor = 'transparent';
            }}
          />

          <select
            value={document.profileId || ''}
            onChange={(e) => handleProfileChange(e.target.value)}
            style={{
              padding: '0.25rem 0.5rem',
              fontSize: '0.875rem',
              background: 'var(--bg-tertiary)',
              border: '1px solid var(--border-color)',
              borderRadius: 'var(--radius-sm)',
              color: 'var(--accent-primary)',
            }}
          >
            <option value="">Без профиля</option>
            {profiles.map((p) => (
              <option key={p.id} value={p.id}>
                {p.name}
              </option>
            ))}
          </select>
        </div>

        <div className="toolbar-group">
          <button
            className="btn btn-secondary btn-sm"
            onClick={() => navigate(`/document/${id}/customize`)}
          >
            ✏️ Редактировать стили
          </button>
          <button className="btn btn-secondary btn-sm" onClick={handleSave} disabled={saving}>
            {saving ? '💾 Сохранение...' : '💾 Сохранить'}
          </button>
          <button
            className="btn btn-primary btn-sm"
            onClick={handleGeneratePdf}
            disabled={generating}
          >
            {generating ? '⏳ Генерация...' : '📥 Скачать PDF'}
          </button>
        </div>
      </div>

      {/* Split view */}
      <div className="split-view">
        {/* Editor */}
        <div className="split-pane split-pane-left" style={{ position: 'relative' }}>
          <textarea
            ref={textareaRef}
            className="code-editor"
            value={document.content}
            onChange={(e) => handleContentChange(e.target.value)}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            onPaste={handlePaste}
            placeholder={`Введите Markdown...

# Заголовок
Обычный параграф текста.

Формулы: $E=mc^2$ или $$\\int_0^1 x^2 dx$$

Перетащите изображение или Ctrl+V`}
            spellCheck={false}
            style={{
              borderColor: isDragging ? 'var(--accent-primary)' : undefined,
              background: isDragging ? 'rgba(122, 162, 247, 0.1)' : undefined,
            }}
          />

          {uploading && (
            <div
              style={{
                position: 'absolute',
                top: '50%',
                left: '50%',
                transform: 'translate(-50%, -50%)',
                background: 'var(--bg-elevated)',
                padding: '1rem 2rem',
                borderRadius: 'var(--radius-md)',
                boxShadow: 'var(--shadow-lg)',
              }}
            >
              ⏳ Загрузка изображения...
            </div>
          )}

          {isDragging && (
            <div
              style={{
                position: 'absolute',
                inset: 0,
                background: 'rgba(122, 162, 247, 0.2)',
                border: '3px dashed var(--accent-primary)',
                borderRadius: 'var(--radius-md)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                pointerEvents: 'none',
              }}
            >
              <span
                style={{
                  fontSize: '1.5rem',
                  color: 'var(--accent-primary)',
                  background: 'var(--bg-elevated)',
                  padding: '1rem 2rem',
                  borderRadius: 'var(--radius-md)',
                }}
              >
                📷 Отпустите для загрузки
              </span>
            </div>
          )}
        </div>

        {/* Preview */}
        <div className="split-pane">
          <DocumentPreview html={renderedHtml} profile={profile} />
        </div>
      </div>
    </div>
  );
}

// frontend/src/pages/document/DocumentEditorPage.vue
<template>
	<div class="document-editor-page">
		<div v-if="loading" class="loading-state">
			<div class="loading-text">Загрузка...</div>
		</div>

		<div v-else-if="!document" class="error-state">
			<div class="error-text">Документ не найден</div>
		</div>

		<div v-else class="editor-container">
			<!-- Header -->
			<div class="editor-header">
				<div class="header-left">
					<button class="back-btn" @click="handleBack">
						← Назад
					</button>
					<input
						type="text"
						class="document-name-input"
						:value="document.name"
						@input="handleNameChange($event)"
					/>
					<select
						class="profile-select"
						:value="document.profileId || ''"
						@change="handleProfileChange($event)"
					>
						<option value="">Без профиля</option>
						<option
							v-for="p in profiles"
							:key="p.id"
							:value="p.id"
						>
							{{ p.name }}
						</option>
					</select>
				</div>
				<button class="save-btn" @click="handleSave" :disabled="saving">
					{{ saving ? 'Сохранение...' : 'Сохранить' }}
				</button>
			</div>

			<!-- Main Content -->
			<div class="editor-content">
				<ResizableSplitView :initial-left-width="50">
					<template #left>
						<div class="editor-pane" :class="{ 'is-dragging': isDragging }">
							<textarea
								ref="textareaRef"
								class="markdown-editor"
								:value="document.content"
								@input="handleContentChange($event)"
								@dragover="handleDragOver"
								@dragleave="handleDragLeave"
								@drop="handleDrop"
								@paste="handlePaste"
								placeholder="Введите Markdown...

# Заголовок
Обычный параграф текста.

Формулы: $E=mc^2$ или $$\int_0^1 x^2 dx$$

Перетащите изображение или Ctrl+V"
								spellcheck="false"
							/>
							<div v-if="uploading || isDragging" class="upload-overlay">
								<div v-if="uploading" class="upload-indicator">
									⏳ Загрузка изображения...
								</div>
								<div v-else-if="isDragging" class="drag-indicator">
									📷 Отпустите для загрузки
								</div>
							</div>
						</div>
					</template>
					<template #right>
						<DocumentPreview
							:html="renderedHtml"
							:profile="profile"
							:document-variables="documentVariables"
						/>
					</template>
				</ResizableSplitView>
			</div>
		</div>
	</div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useDocumentEditor } from '@/widgets/document/useDocumentEditor';
import ResizableSplitView from '@/widgets/document/ResizableSplitView.vue';
import DocumentPreview from '@/widgets/document/DocumentPreview.vue';
import { renderDocument } from '@/shared/services/markdown/documentRenderer';

const route = useRoute();
const router = useRouter();
const documentId = route.params.id as string;

const {
	document,
	profile,
	profiles,
	loading,
	saving,
	uploading,
	textareaRef,
	handleSave: handleSaveInternal,
	handleNameChange: handleNameChangeInternal,
	handleContentChange: handleContentChangeInternal,
	handleProfileChange: handleProfileChangeInternal,
	handleImageUpload: handleImageUploadInternal,
} = useDocumentEditor(documentId);

const isDragging = ref(false);

function handleBack() {
	router.push('/dashboard');
}

function handleSave() {
	handleSaveInternal();
}

function handleNameChange(event: Event) {
	const target = event.target as HTMLInputElement;
	handleNameChangeInternal(target.value);
}

function handleContentChange(event: Event) {
	const target = event.target as HTMLTextAreaElement;
	handleContentChangeInternal(target.value);
}

function handleProfileChange(event: Event) {
	const target = event.target as HTMLSelectElement;
	handleProfileChangeInternal(target.value);
}

function handleDragOver(event: DragEvent) {
	event.preventDefault();
	isDragging.value = true;
}

function handleDragLeave(event: DragEvent) {
	event.preventDefault();
	isDragging.value = false;
}

function handleDrop(event: DragEvent) {
	event.preventDefault();
	isDragging.value = false;

	const files = event.dataTransfer?.files;
	if (files && files.length > 0 && files[0].type.startsWith('image/')) {
		handleImageUploadInternal(files[0]);
	}
}

function handlePaste(event: ClipboardEvent) {
	const items = event.clipboardData?.items;
	if (!items) return;

	for (let i = 0; i < items.length; i++) {
		const item = items[i];
		if (item.type.startsWith('image/')) {
			event.preventDefault();
			const file = item.getAsFile();
			if (file) {
				handleImageUploadInternal(file);
			}
			break;
		}
	}
}

const documentVariables = computed(() => {
	// Extract variables from frontmatter if needed
	// For now, return empty object
	return {};
});

const renderedHtml = computed(() => {
	if (!document.value) return '';
	
	return renderDocument({
		markdown: document.value.content,
		profile: profile.value,
		overrides: {},
		selectable: false,
	});
});
</script>

<style scoped>
.document-editor-page {
	min-height: 100vh;
	background: #0a0a0a;
	color: #e4e4e7;
}

.loading-state,
.error-state {
	display: flex;
	align-items: center;
	justify-content: center;
	min-height: 100vh;
}

.loading-text,
.error-text {
	font-size: 16px;
	color: #71717a;
}

.editor-container {
	display: flex;
	flex-direction: column;
	height: 100vh;
	overflow: hidden;
}

.editor-header {
	display: flex;
	justify-content: space-between;
	align-items: center;
	padding: 2rem;
	border-bottom: 1px solid #27272a;
	background: #0a0a0a;
}

.header-left {
	display: flex;
	align-items: center;
	gap: 1rem;
}

.back-btn {
	padding: 0.5rem 1rem;
	background: transparent;
	border: 1px solid #27272a;
	border-radius: 6px;
	color: #a1a1aa;
	font-size: 14px;
	cursor: pointer;
	transition: all 0.2s;
	font-family: inherit;
}

.back-btn:hover {
	background: #27272a;
	color: #e4e4e7;
	border-color: #3f3f46;
}

.document-name-input {
	padding: 0.5rem 0.75rem;
	background: transparent;
	border: 1px solid transparent;
	border-radius: 6px;
	color: #e4e4e7;
	font-size: 20px;
	font-weight: 600;
	outline: none;
	transition: all 0.2s;
	font-family: inherit;
	width: 300px;
}

.document-name-input:focus {
	background: #18181b;
	border-color: #6366f1;
}

.profile-select {
	padding: 0.5rem 0.75rem;
	background: #18181b;
	border: 1px solid #27272a;
	border-radius: 6px;
	color: #e4e4e7;
	font-size: 14px;
	font-family: inherit;
	outline: none;
	transition: all 0.2s;
	cursor: pointer;
}

.profile-select:hover {
	border-color: #3f3f46;
}

.profile-select:focus {
	border-color: #6366f1;
	background: #27272a;
}

.save-btn {
	padding: 0.75rem 1.5rem;
	background: #6366f1;
	color: white;
	border: none;
	border-radius: 8px;
	font-size: 14px;
	font-weight: 600;
	cursor: pointer;
	transition: background 0.2s;
	font-family: inherit;
}

.save-btn:hover:not(:disabled) {
	background: #818cf8;
}

.save-btn:disabled {
	opacity: 0.5;
	cursor: not-allowed;
}

.editor-content {
	flex: 1;
	overflow: hidden;
	display: flex;
	flex-direction: column;
	min-height: 0;
}

.editor-pane {
	height: 100%;
	display: flex;
	flex-direction: column;
	overflow: hidden;
	min-height: 0;
}

.markdown-editor {
	width: 100%;
	flex: 1;
	min-height: 0;
	padding: 1.5rem;
	background: #0a0a0a;
	border: none;
	color: #e4e4e7;
	font-family: 'Courier New', Courier, monospace;
	font-size: 14px;
	line-height: 1.6;
	resize: none;
	outline: none;
	tab-size: 2;
	box-sizing: border-box;
}

.markdown-editor::placeholder {
	color: #71717a;
}

.editor-pane {
	position: relative;
}

.editor-pane.is-dragging .markdown-editor {
	border-color: #6366f1;
}

.upload-overlay {
	position: absolute;
	inset: 0;
	display: flex;
	align-items: center;
	justify-content: center;
	pointer-events: none;
	z-index: 10;
}

.upload-indicator,
.drag-indicator {
	background: #18181b;
	padding: 1rem 2rem;
	border-radius: 8px;
	border: 2px solid #6366f1;
	color: #e4e4e7;
	font-size: 14px;
	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
}

.drag-indicator {
	background: rgba(99, 102, 241, 0.1);
	border: 3px dashed #6366f1;
	font-size: 16px;
}

</style>
