// client/src/presentation/components/EntityStyleEditor.tsx
import { useState, useEffect } from 'react';
import type { EntityStyle, EntityType } from '../../../../shared/src/types';
import { ENTITY_LABELS, FONT_FAMILIES, DEFAULT_ENTITY_STYLES } from '../../../../shared/src/types';

interface EntityStyleEditorProps {
  entityType: EntityType;
  style: EntityStyle;
  onChange: (style: EntityStyle) => void;
  title?: string;
  showReset?: boolean;
  onReset?: () => void;
}

/**
 * Editor component for entity styles
 * Allows editing all style properties for any entity type
 */
export function EntityStyleEditor({
  entityType,
  style,
  onChange,
  title,
  showReset = false,
  onReset,
}: EntityStyleEditorProps) {
  const [localStyle, setLocalStyle] = useState<EntityStyle>(style);

  useEffect(() => {
    setLocalStyle(style);
  }, [style]);

  const updateStyle = (key: keyof EntityStyle, value: unknown) => {
    const newStyle = { ...localStyle, [key]: value };
    setLocalStyle(newStyle);
    onChange(newStyle);
  };

  const updateNumericStyle = (key: keyof EntityStyle, value: string, allowFloat = false) => {
    if (value === '') {
      const newStyle = { ...localStyle };
      delete newStyle[key];
      setLocalStyle(newStyle);
      onChange(newStyle);
      return;
    }
    const num = allowFloat ? parseFloat(value) : parseInt(value, 10);
    if (!isNaN(num)) {
      updateStyle(key, num);
    }
  };

  const getDefaultValue = (key: keyof EntityStyle) => {
    return DEFAULT_ENTITY_STYLES[entityType]?.[key];
  };

  const displayTitle = title || ENTITY_LABELS[entityType];

  // Determine which sections to show based on entity type
  const showTypography = ['paragraph', 'heading', 'image-caption', 'table-caption', 'formula-caption', 'ordered-list', 'unordered-list', 'table'].includes(entityType);
  const showTextFormat = ['paragraph', 'heading', 'image-caption', 'table-caption', 'formula-caption', 'image', 'formula'].includes(entityType);
  const showIndent = ['paragraph', 'ordered-list', 'unordered-list'].includes(entityType);
  const showBorder = ['table'].includes(entityType);
  const showMaxWidth = ['image'].includes(entityType);

  return (
    <div className="style-editor">
      <div className="style-editor-header">
        <span className="style-editor-title">{displayTitle}</span>
        {showReset && onReset && (
          <button className="btn btn-ghost btn-sm" onClick={onReset}>
            Сбросить
          </button>
        )}
      </div>

      <div className="style-editor-content">
        {/* Typography Section */}
        {showTypography && (
          <div className="style-section">
            <div className="style-section-title">Типографика</div>
            <div className="form-row">
              <div className="form-group">
                <label className="form-label">Размер (pt)</label>
                <input
                  type="number"
                  className="form-input form-input-sm"
                  value={localStyle.fontSize ?? ''}
                  placeholder={String(getDefaultValue('fontSize') ?? '')}
                  onChange={(e) => updateNumericStyle('fontSize', e.target.value)}
                  min={6}
                  max={72}
                />
              </div>

              <div className="form-group">
                <label className="form-label">Шрифт</label>
                <select
                  className="form-select form-input-sm"
                  value={localStyle.fontFamily ?? ''}
                  onChange={(e) => updateStyle('fontFamily', e.target.value || undefined)}
                >
                  {FONT_FAMILIES.map((font) => (
                    <option key={font.value} value={font.value}>
                      {font.label}
                    </option>
                  ))}
                </select>
              </div>

              <div className="form-group">
                <label className="form-label">Жирность</label>
                <select
                  className="form-select form-input-sm"
                  value={localStyle.fontWeight ?? ''}
                  onChange={(e) => updateStyle('fontWeight', e.target.value || undefined)}
                >
                  <option value="">По умолч.</option>
                  <option value="normal">Обычный</option>
                  <option value="bold">Жирный</option>
                </select>
              </div>

              <div className="form-group">
                <label className="form-label">Начертание</label>
                <select
                  className="form-select form-input-sm"
                  value={localStyle.fontStyle ?? ''}
                  onChange={(e) => updateStyle('fontStyle', e.target.value || undefined)}
                >
                  <option value="">По умолч.</option>
                  <option value="normal">Обычный</option>
                  <option value="italic">Курсив</option>
                </select>
              </div>
            </div>
          </div>
        )}

        {/* Text Formatting Section */}
        {showTextFormat && (
          <div className="style-section">
            <div className="style-section-title">Форматирование</div>
            <div className="form-row">
              <div className="form-group">
                <label className="form-label">Выравнивание</label>
                <select
                  className="form-select form-input-sm"
                  value={localStyle.textAlign ?? ''}
                  onChange={(e) => updateStyle('textAlign', e.target.value || undefined)}
                >
                  <option value="">По умолч.</option>
                  <option value="left">По левому</option>
                  <option value="center">По центру</option>
                  <option value="right">По правому</option>
                  <option value="justify">По ширине</option>
                </select>
              </div>

              {showIndent && (
                <div className="form-group">
                  <label className="form-label">Красная строка (см)</label>
                  <input
                    type="number"
                    className="form-input form-input-sm"
                    value={localStyle.textIndent ?? ''}
                    placeholder={String(getDefaultValue('textIndent') ?? '')}
                    onChange={(e) => updateNumericStyle('textIndent', e.target.value, true)}
                    step={0.25}
                    min={0}
                    max={5}
                  />
                </div>
              )}

              <div className="form-group">
                <label className="form-label">Межстрочный интервал</label>
                <input
                  type="number"
                  className="form-input form-input-sm"
                  value={localStyle.lineHeight ?? ''}
                  placeholder={String(getDefaultValue('lineHeight') ?? '')}
                  onChange={(e) => updateNumericStyle('lineHeight', e.target.value, true)}
                  step={0.1}
                  min={0.5}
                  max={3}
                />
              </div>
            </div>
          </div>
        )}

        {/* Margins Section */}
        <div className="style-section">
          <div className="style-section-title">Внешние отступы (pt)</div>
          <div className="form-row">
            <div className="form-group">
              <label className="form-label">Сверху</label>
              <input
                type="number"
                className="form-input form-input-sm"
                value={localStyle.marginTop ?? ''}
                placeholder={String(getDefaultValue('marginTop') ?? '')}
                onChange={(e) => updateNumericStyle('marginTop', e.target.value)}
                min={0}
                max={200}
              />
            </div>

            <div className="form-group">
              <label className="form-label">Снизу</label>
              <input
                type="number"
                className="form-input form-input-sm"
                value={localStyle.marginBottom ?? ''}
                placeholder={String(getDefaultValue('marginBottom') ?? '')}
                onChange={(e) => updateNumericStyle('marginBottom', e.target.value)}
                min={0}
                max={200}
              />
            </div>

            <div className="form-group">
              <label className="form-label">Слева</label>
              <input
                type="number"
                className="form-input form-input-sm"
                value={localStyle.marginLeft ?? ''}
                placeholder={String(getDefaultValue('marginLeft') ?? '')}
                onChange={(e) => updateNumericStyle('marginLeft', e.target.value)}
                min={0}
                max={200}
              />
            </div>

            <div className="form-group">
              <label className="form-label">Справа</label>
              <input
                type="number"
                className="form-input form-input-sm"
                value={localStyle.marginRight ?? ''}
                placeholder={String(getDefaultValue('marginRight') ?? '')}
                onChange={(e) => updateNumericStyle('marginRight', e.target.value)}
                min={0}
                max={200}
              />
            </div>
          </div>
        </div>

        {/* Border Section (for tables) */}
        {showBorder && (
          <div className="style-section">
            <div className="style-section-title">Рамка</div>
            <div className="form-row">
              <div className="form-group">
                <label className="form-label">Толщина (px)</label>
                <input
                  type="number"
                  className="form-input form-input-sm"
                  value={localStyle.borderWidth ?? ''}
                  placeholder={String(getDefaultValue('borderWidth') ?? '')}
                  onChange={(e) => updateNumericStyle('borderWidth', e.target.value)}
                  min={0}
                  max={10}
                />
              </div>

              <div className="form-group">
                <label className="form-label">Стиль</label>
                <select
                  className="form-select form-input-sm"
                  value={localStyle.borderStyle ?? ''}
                  onChange={(e) => updateStyle('borderStyle', e.target.value || undefined)}
                >
                  <option value="">По умолч.</option>
                  <option value="none">Нет</option>
                  <option value="solid">Сплошная</option>
                  <option value="dashed">Пунктир</option>
                </select>
              </div>

              <div className="form-group">
                <label className="form-label">Цвет</label>
                <input
                  type="color"
                  className="form-input form-input-sm"
                  value={localStyle.borderColor ?? '#333333'}
                  onChange={(e) => updateStyle('borderColor', e.target.value)}
                  style={{ padding: 2, height: 32 }}
                />
              </div>
            </div>
          </div>
        )}

        {/* Size Section (for images) */}
        {showMaxWidth && (
          <div className="style-section">
            <div className="style-section-title">Размер</div>
            <div className="form-row">
              <div className="form-group">
                <label className="form-label">Макс. ширина (%)</label>
                <input
                  type="number"
                  className="form-input form-input-sm"
                  value={localStyle.maxWidth ?? ''}
                  placeholder={String(getDefaultValue('maxWidth') ?? '')}
                  onChange={(e) => updateNumericStyle('maxWidth', e.target.value)}
                  min={10}
                  max={100}
                />
              </div>
            </div>
          </div>
        )}

        {/* Colors Section */}
        <div className="style-section">
          <div className="style-section-title">Цвета</div>
          <div className="form-row">
            <div className="form-group">
              <label className="form-label">Цвет текста</label>
              <input
                type="color"
                className="form-input form-input-sm"
                value={localStyle.color ?? '#000000'}
                onChange={(e) => updateStyle('color', e.target.value)}
                style={{ padding: 2, height: 32 }}
              />
            </div>

            <div className="form-group">
              <label className="form-label">Фон</label>
              <input
                type="color"
                className="form-input form-input-sm"
                value={localStyle.backgroundColor ?? '#ffffff'}
                onChange={(e) => updateStyle('backgroundColor', e.target.value)}
                style={{ padding: 2, height: 32 }}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/widgets/profile/EntityStyleEditor.vue
<template>
	<div class="style-editor">
		<div class="style-editor-header">
			<span class="style-editor-title">{{ displayTitle }}</span>
			<button
				v-if="showReset"
				class="btn btn-ghost btn-sm"
				@click="$emit('reset')"
			>
				Сбросить
			</button>
		</div>

		<div class="style-editor-content">
			<!-- Typography Section -->
			<template
				v-if="
					['paragraph', 'heading', 'image-caption', 'table-caption', 'formula-caption', 'ordered-list', 'unordered-list', 'table'].includes(
						entityType,
					)
				"
			>
				<div class="style-section">
					<div class="style-section-title">Типографика</div>
					<div class="form-row">
						<div class="form-group">
							<label class="form-label">Размер (pt)</label>
							<input
								type="number"
								class="form-input form-input-sm"
								:value="localStyle.fontSize ?? ''"
								@input="updateNumericStyle('fontSize', $event)"
								min="6"
								max="72"
							/>
						</div>

						<div class="form-group">
							<label class="form-label">Шрифт</label>
							<select
								class="form-select form-select-sm"
								:value="localStyle.fontFamily ?? ''"
								@change="updateStyle('fontFamily', $event)"
							>
								<option value="">По умолч.</option>
								<option
									v-for="font in FONT_FAMILIES"
									:key="font.value"
									:value="font.value"
								>
									{{ font.label }}
								</option>
							</select>
						</div>

						<div class="form-group">
							<label class="form-label">Жирность</label>
							<select
								class="form-select form-select-sm"
								:value="localStyle.fontWeight ?? ''"
								@change="updateStyle('fontWeight', $event)"
							>
								<option value="">По умолч.</option>
								<option value="normal">Обычный</option>
								<option value="bold">Жирный</option>
							</select>
						</div>

						<div class="form-group">
							<label class="form-label">Начертание</label>
							<select
								class="form-select form-select-sm"
								:value="localStyle.fontStyle ?? ''"
								@change="updateStyle('fontStyle', $event)"
							>
								<option value="">По умолч.</option>
								<option value="normal">Обычный</option>
								<option value="italic">Курсив</option>
							</select>
						</div>
					</div>
				</div>
			</template>

			<!-- Text Formatting Section -->
			<template
				v-if="
					['paragraph', 'heading', 'image-caption', 'table-caption', 'formula-caption', 'image', 'formula'].includes(
						entityType,
					)
				"
			>
				<div class="style-section">
					<div class="style-section-title">Форматирование</div>
					<div class="form-row">
						<div class="form-group">
							<label class="form-label">Выравнивание</label>
							<select
								class="form-select form-select-sm"
								:value="localStyle.textAlign ?? ''"
								@change="updateStyle('textAlign', $event)"
							>
								<option value="">По умолч.</option>
								<option value="left">По левому</option>
								<option value="center">По центру</option>
								<option value="right">По правому</option>
								<option value="justify">По ширине</option>
							</select>
						</div>

						<template
							v-if="['paragraph', 'ordered-list', 'unordered-list'].includes(entityType)"
						>
							<div class="form-group">
								<label class="form-label">Красная строка (см)</label>
								<input
									type="number"
									class="form-input form-input-sm"
									:value="localStyle.textIndent ?? ''"
									@input="updateNumericStyle('textIndent', $event, true)"
									step="0.25"
									min="0"
									max="5"
								/>
							</div>
						</template>

						<div class="form-group">
							<label class="form-label">Межстрочный интервал</label>
							<input
								type="number"
								class="form-input form-input-sm"
								:value="localStyle.lineHeight ?? ''"
								@input="updateNumericStyle('lineHeight', $event, true)"
								step="0.1"
								min="0.5"
								max="3"
							/>
						</div>
					</div>
				</div>
			</template>

			<!-- Margins Section -->
			<div class="style-section">
				<div class="style-section-title">Внешние отступы (pt)</div>
				<div class="form-row">
					<div class="form-group">
						<label class="form-label">Сверху</label>
						<input
							type="number"
							class="form-input form-input-sm"
							:value="localStyle.marginTop ?? ''"
							@input="updateNumericStyle('marginTop', $event)"
							min="0"
							max="200"
						/>
					</div>

					<div class="form-group">
						<label class="form-label">Снизу</label>
						<input
							type="number"
							class="form-input form-input-sm"
							:value="localStyle.marginBottom ?? ''"
							@input="updateNumericStyle('marginBottom', $event)"
							min="0"
							max="200"
						/>
					</div>

					<div class="form-group">
						<label class="form-label">Слева</label>
						<input
							type="number"
							class="form-input form-input-sm"
							:value="localStyle.marginLeft ?? ''"
							@input="updateNumericStyle('marginLeft', $event)"
							min="0"
							max="200"
						/>
					</div>

					<div class="form-group">
						<label class="form-label">Справа</label>
						<input
							type="number"
							class="form-input form-input-sm"
							:value="localStyle.marginRight ?? ''"
							@input="updateNumericStyle('marginRight', $event)"
							min="0"
							max="200"
						/>
					</div>
				</div>
			</div>

			<!-- Border Section (for tables) -->
			<template v-if="entityType === 'table'">
				<div class="style-section">
					<div class="style-section-title">Границы</div>
					<div class="form-row">
						<div class="form-group">
							<label class="form-label">Ширина (px)</label>
							<input
								type="number"
								class="form-input form-input-sm"
								:value="localStyle.borderWidth ?? ''"
								@input="updateNumericStyle('borderWidth', $event)"
								min="0"
								max="10"
							/>
						</div>

						<div class="form-group">
							<label class="form-label">Цвет</label>
							<input
								type="color"
								class="form-input form-input-sm color-input"
								:value="localStyle.borderColor || '#000000'"
								@input="updateStyle('borderColor', $event)"
							/>
						</div>

						<div class="form-group">
							<label class="form-label">Стиль</label>
							<select
								class="form-select form-select-sm"
								:value="localStyle.borderStyle ?? 'solid'"
								@change="updateStyle('borderStyle', $event)"
							>
								<option value="none">Нет</option>
								<option value="solid">Сплошная</option>
								<option value="dashed">Пунктир</option>
							</select>
						</div>
					</div>
				</div>
			</template>

			<!-- Max Width Section (for images) -->
			<template v-if="entityType === 'image'">
				<div class="style-section">
					<div class="style-section-title">Размер</div>
					<div class="form-row">
						<div class="form-group">
							<label class="form-label">Макс. ширина (%)</label>
							<input
								type="number"
								class="form-input form-input-sm"
								:value="localStyle.maxWidth ?? ''"
								@input="updateNumericStyle('maxWidth', $event)"
								min="0"
								max="100"
							/>
						</div>
					</div>
				</div>
			</template>
		</div>
	</div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import type { EntityType } from '@/entities/profile/constants';
import { ENTITY_LABELS, FONT_FAMILIES } from '@/entities/profile/constants';

interface Props {
	entityType: EntityType;
	style: Record<string, any>;
	title?: string;
	showReset?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
	showReset: false,
});

const emit = defineEmits<{
	change: [style: Record<string, any>];
	reset: [];
}>();

const localStyle = ref<Record<string, any>>({ ...props.style });

watch(
	() => props.style,
	(newStyle) => {
		localStyle.value = { ...newStyle };
	},
	{ deep: true },
);

const displayTitle = props.title || ENTITY_LABELS[props.entityType];

function updateStyle(key: string, event: Event) {
	const target = event.target as HTMLSelectElement | HTMLInputElement;
	const value = target.value || undefined;
	const newStyle = { ...localStyle.value };
	if (value === undefined || value === '') {
		delete newStyle[key];
	} else {
		newStyle[key] = value;
	}
	localStyle.value = newStyle;
	emit('change', newStyle);
}

function updateNumericStyle(key: string, event: Event, allowFloat = false) {
	const target = event.target as HTMLInputElement;
	const value = target.value;
	if (value === '') {
		const newStyle = { ...localStyle.value };
		delete newStyle[key];
		localStyle.value = newStyle;
		emit('change', newStyle);
		return;
	}
	const num = allowFloat ? parseFloat(value) : parseInt(value, 10);
	if (!isNaN(num)) {
		const newStyle = { ...localStyle.value, [key]: num };
		localStyle.value = newStyle;
		emit('change', newStyle);
	}
}
</script>

<style scoped>
.style-editor {
	background: #18181b;
	border: 1px solid #27272a;
	border-radius: 8px;
	padding: 1.5rem;
}

.style-editor-header {
	display: flex;
	justify-content: space-between;
	align-items: center;
	margin-bottom: 1.5rem;
}

.style-editor-title {
	font-size: 18px;
	font-weight: 600;
	color: #e4e4e7;
}

.btn {
	padding: 0.5rem 1rem;
	border-radius: 6px;
	font-size: 13px;
	font-weight: 500;
	cursor: pointer;
	transition: all 0.2s;
	border: none;
	font-family: inherit;
}

.btn-ghost {
	background: transparent;
	color: #a1a1aa;
	border: 1px solid #27272a;
}

.btn-ghost:hover {
	background: #27272a;
	color: #e4e4e7;
}

.btn-sm {
	padding: 0.4rem 0.75rem;
	font-size: 12px;
}

.style-editor-content {
	display: flex;
	flex-direction: column;
	gap: 1.5rem;
}

.style-section {
	display: flex;
	flex-direction: column;
	gap: 0.75rem;
}

.style-section-title {
	font-size: 14px;
	font-weight: 600;
	color: #a1a1aa;
	text-transform: uppercase;
	letter-spacing: 0.5px;
}

.form-row {
	display: grid;
	grid-template-columns: repeat(4, 1fr);
	gap: 0.75rem;
}

.form-group {
	display: flex;
	flex-direction: column;
}

.form-label {
	font-size: 12px;
	font-weight: 500;
	color: #71717a;
	margin-bottom: 0.4rem;
}

.form-input,
.form-select {
	width: 100%;
	padding: 0.5rem 0.75rem;
	background: #0a0a0a;
	border: 1px solid #27272a;
	border-radius: 6px;
	color: #e4e4e7;
	font-size: 13px;
	outline: none;
	transition: border-color 0.2s;
	font-family: inherit;
}

.form-input-sm,
.form-select-sm {
	padding: 0.4rem 0.6rem;
	font-size: 12px;
}

.color-input {
	height: 36px;
	cursor: pointer;
}

.form-input:focus,
.form-select:focus {
	border-color: #6366f1;
}

.form-select option {
	background: #18181b;
	color: #e4e4e7;
}

.form-input::placeholder {
	color: #71717a;
}
</style>
