// client/src/presentation/components/DocumentPreview.tsx
import { useMemo, useRef, useEffect, useState } from 'react';
import type { Profile, TitlePage } from '../../../../shared/src/types';
import { DEFAULT_PAGE_SETTINGS } from '../../../../shared/src/types';
import { PAGE_SIZES, MM_TO_PX } from '../../../../shared/src/constants';
import { titlePageApi } from '../../infrastructure/api/titlePageApi';
import { getDefaultTitlePageId } from '../../utils/storageUtils';
import { renderTitlePageToHtml } from '../../application/services/titlePageRenderer';

interface DocumentPreviewProps {
  html: string;
  profile: Profile | null;
  onClick?: (e: React.MouseEvent) => void;
  documentVariables?: Record<string, string>;
}

interface PageDimensions {
  pageWidth: number;
  pageHeight: number;
  marginTop: number;
  marginRight: number;
  marginBottom: number;
  marginLeft: number;
}

/**
 * Calculate page dimensions based on profile settings
 */
function calculateDimensions(profile: Profile | null): PageDimensions {
  const settings = profile?.page || DEFAULT_PAGE_SETTINGS;
  const size = PAGE_SIZES[settings.size] || PAGE_SIZES.A4;
  const isLandscape = settings.orientation === 'landscape';

  const pageWidth = (isLandscape ? size.height : size.width) * MM_TO_PX;
  const pageHeight = (isLandscape ? size.width : size.height) * MM_TO_PX;

  return {
    pageWidth,
    pageHeight,
    marginTop: settings.margins.top * MM_TO_PX,
    marginRight: settings.margins.right * MM_TO_PX,
    marginBottom: settings.margins.bottom * MM_TO_PX,
    marginLeft: settings.margins.left * MM_TO_PX,
  };
}

/**
 * Render page number based on settings
 */
function renderPageNumber(
  pageNumber: number,
  totalPages: number,
  pageNumbers: Profile['page']['pageNumbers'],
  position: 'top' | 'bottom'
): string {
  if (!pageNumbers?.enabled) {
    return '';
  }

  const format = pageNumbers.format
    .replace('{n}', String(pageNumber))
    .replace('{total}', String(totalPages));

  const fontSize = pageNumbers.fontSize || 12;
  const fontFamily = pageNumbers.fontFamily ? `font-family: ${pageNumbers.fontFamily};` : '';
  const fontStyle = pageNumbers.fontStyle ? `font-style: ${pageNumbers.fontStyle};` : '';
  const textAlign = `text-align: ${pageNumbers.align};`;
  
  // Add padding-bottom for footer to raise page number slightly
  const paddingBottom = position === 'bottom' ? 'padding-bottom: 6px;' : '';

  return `
    <div style="${fontFamily} ${fontStyle} font-size: ${fontSize}pt; ${textAlign} width: 100%; color: #000; ${paddingBottom}">
      ${format}
    </div>
  `;
}

/**
 * Split HTML content into pages based on content height
 * Elements are never split - they are moved to next page if they don't fit
 */
function splitIntoPages(
  html: string,
  pageContentHeight: number,
  contentWidth: number
): string[] {
  if (!html.trim()) {
    return [html];
  }

  // Create a temporary container WITHOUT padding to measure elements accurately
  const tempContainer = document.createElement('div');
  tempContainer.style.position = 'absolute';
  tempContainer.style.visibility = 'hidden';
  tempContainer.style.width = `${contentWidth}px`;
  // NO padding here - we measure elements without padding
  tempContainer.style.fontFamily = "'Times New Roman', Times, serif";
  tempContainer.style.fontSize = '14pt';
  tempContainer.style.lineHeight = '1.5';
  tempContainer.style.color = '#1a1a1a';
  document.body.appendChild(tempContainer);

  // First, measure total content height WITHOUT padding to check if splitting is needed
  // pageContentHeight is already calculated without padding, so we measure without padding too
  const totalContainer = document.createElement('div');
  totalContainer.style.position = 'absolute';
  totalContainer.style.visibility = 'hidden';
  totalContainer.style.width = `${contentWidth}px`;
  // NO padding here - we measure content height without padding to match pageContentHeight
  totalContainer.style.fontFamily = "'Times New Roman', Times, serif";
  totalContainer.style.fontSize = '14pt';
  totalContainer.style.lineHeight = '1.5';
  totalContainer.style.color = '#1a1a1a';
  totalContainer.innerHTML = html;
  document.body.appendChild(totalContainer);

  const totalHeight = totalContainer.scrollHeight;
  document.body.removeChild(totalContainer);
  
  // If content fits in one page, return as is
  if (totalHeight <= pageContentHeight) {
    document.body.removeChild(tempContainer);
    return [html];
  }

  // Parse HTML to get individual elements
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');
  const body = doc.body;
  
  const pages: string[] = [];
  const elements = Array.from(body.children);
  let currentPageElements: Element[] = [];

  // Elements that should not be split (block-level elements)
  const blockElements = new Set(['P', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'UL', 'OL', 'LI', 'TABLE', 'TR', 'THEAD', 'TBODY', 'DIV']);

  for (const element of elements) {
    // Measure this element WITHOUT padding
    const elementClone = element.cloneNode(true) as HTMLElement;
    tempContainer.innerHTML = '';
    tempContainer.appendChild(elementClone);
    const elementHeight = tempContainer.scrollHeight;

    // Check if element should not be split
    const isBlockElement = blockElements.has(element.tagName);
    
    // If element alone exceeds page height and it's a block element, put it on its own page
    if (elementHeight > pageContentHeight && isBlockElement) {
      // Save current page if it has content
      if (currentPageElements.length > 0) {
        const pageDiv = document.createElement('div');
        currentPageElements.forEach(el => pageDiv.appendChild(el.cloneNode(true)));
        pages.push(pageDiv.innerHTML);
        currentPageElements = [];
      }

      // Put large element on its own page
      const pageDiv = document.createElement('div');
      pageDiv.appendChild(element.cloneNode(true));
      pages.push(pageDiv.innerHTML);
      continue;
    }

    // Measure combined height of current page + new element
    // This gives us more accurate measurement than just summing heights
    if (currentPageElements.length > 0) {
      const testContainer = document.createElement('div');
      testContainer.style.position = 'absolute';
      testContainer.style.visibility = 'hidden';
      testContainer.style.width = `${contentWidth}px`;
      testContainer.style.fontFamily = "'Times New Roman', Times, serif";
      testContainer.style.fontSize = '14pt';
      testContainer.style.lineHeight = '1.5';
      testContainer.style.color = '#1a1a1a';
      
      const testPageDiv = document.createElement('div');
      currentPageElements.forEach(el => testPageDiv.appendChild(el.cloneNode(true)));
      testPageDiv.appendChild(element.cloneNode(true));
      testContainer.appendChild(testPageDiv);
      document.body.appendChild(testContainer);
      
      const combinedHeight = testContainer.scrollHeight;
      document.body.removeChild(testContainer);
      
      // Check if combined height exceeds page height
      if (combinedHeight > pageContentHeight) {
        // Start new page
        const pageDiv = document.createElement('div');
        currentPageElements.forEach(el => pageDiv.appendChild(el.cloneNode(true)));
        pages.push(pageDiv.innerHTML);
        currentPageElements = [element];
      } else {
        // Add to current page
        currentPageElements.push(element);
      }
    } else {
      // First element on page
      currentPageElements.push(element);
    }
  }

  // Add remaining elements as last page
  if (currentPageElements.length > 0) {
    const pageDiv = document.createElement('div');
    currentPageElements.forEach(el => pageDiv.appendChild(el.cloneNode(true)));
    pages.push(pageDiv.innerHTML);
  }

  document.body.removeChild(tempContainer);
  return pages.length > 0 ? pages : [html];
}

/**
 * Document Preview Component
 * 
 * Renders document with separate pages, page breaks, and gaps between pages.
 */
export function DocumentPreview({ html, profile, onClick, documentVariables }: DocumentPreviewProps) {
  const dimensions = useMemo(() => calculateDimensions(profile), [profile]);
  const contentRef = useRef<HTMLDivElement>(null);
  const [pages, setPages] = useState<string[]>([html]);
  const [titlePage, setTitlePage] = useState<TitlePage | null>(null);
  const [zoom, setZoom] = useState(100);
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });
  const [scrollPosition, setScrollPosition] = useState({ left: 0, top: 0 });
  const [hasMoved, setHasMoved] = useState(false);
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  const settings = profile?.page || DEFAULT_PAGE_SETTINGS;
  const pageNumbers = settings.pageNumbers;
  const hasPageNumbers = pageNumbers?.enabled || false;
  
  // Measure actual header/footer content heights (without margins)
  const headerContentHeight = useMemo(() => {
    if (!pageNumbers?.enabled || pageNumbers.position !== 'top') {
      return 0;
    }
    const tempDiv = document.createElement('div');
    tempDiv.style.position = 'absolute';
    tempDiv.style.visibility = 'hidden';
    tempDiv.style.width = `${dimensions.pageWidth}px`;
    tempDiv.innerHTML = renderPageNumber(1, 1, pageNumbers, 'top');
    document.body.appendChild(tempDiv);
    const height = tempDiv.scrollHeight;
    document.body.removeChild(tempDiv);
    return height;
  }, [pageNumbers, dimensions]);
  
  // Calculate available content height
  // Content area = page height - margins - header content height
  // Footer is absolutely positioned and doesn't take space in the flow
  const contentHeight = dimensions.pageHeight 
    - dimensions.marginTop 
    - dimensions.marginBottom 
    - headerContentHeight;
  const contentWidth = dimensions.pageWidth - dimensions.marginLeft - dimensions.marginRight;

  // Load title page
  useEffect(() => {
    const titlePageId = getDefaultTitlePageId();
    if (titlePageId) {
      titlePageApi.getById(titlePageId)
        .then(setTitlePage)
        .catch((error) => {
          console.error('Failed to load title page:', error);
          setTitlePage(null);
        });
    } else {
      setTitlePage(null);
    }
  }, []);

  useEffect(() => {
    if (!html) {
      setPages(['']);
      return;
    }

    // Split into pages
    const splitPages = splitIntoPages(html, contentHeight, contentWidth);
    setPages(splitPages);
  }, [html, contentHeight, contentWidth]);

  const totalPages = pages.length;
  
  // Merge documentVariables with titlePage.variables (documentVariables have priority)
  const mergedVariables = useMemo(() => {
    if (!titlePage) return documentVariables || {};
    return {
      ...titlePage.variables,
      ...(documentVariables || {}),
    };
  }, [titlePage, documentVariables]);
  
  const titlePageHtml = titlePage ? renderTitlePageToHtml(titlePage, mergedVariables) : null;

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        background: '#525659',
      }}
    >
      {/* Zoom controls */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem',
          padding: '0.5rem 1rem',
          background: '#3d4043',
          borderBottom: '1px solid #525659',
        }}
      >
        <button
          onClick={() => setZoom(Math.max(50, zoom - 10))}
          style={{
            padding: '0.25rem 0.5rem',
            background: '#525659',
            color: 'white',
            border: '1px solid #6d7073',
            borderRadius: '4px',
            cursor: 'pointer',
            fontSize: '0.875rem',
          }}
          title="Уменьшить масштаб"
        >
          −
        </button>
        <input
          type="range"
          min="50"
          max="200"
          value={zoom}
          onChange={(e) => setZoom(parseInt(e.target.value))}
          style={{
            flex: 1,
            maxWidth: '200px',
          }}
        />
        <span style={{ color: 'white', fontSize: '0.875rem', minWidth: '50px', textAlign: 'center' }}>
          {zoom}%
        </span>
        <button
          onClick={() => setZoom(Math.min(200, zoom + 10))}
          style={{
            padding: '0.25rem 0.5rem',
            background: '#525659',
            color: 'white',
            border: '1px solid #6d7073',
            borderRadius: '4px',
            cursor: 'pointer',
            fontSize: '0.875rem',
          }}
          title="Увеличить масштаб"
        >
          +
        </button>
        <button
          onClick={() => setZoom(100)}
          style={{
            padding: '0.25rem 0.5rem',
            background: '#525659',
            color: 'white',
            border: '1px solid #6d7073',
            borderRadius: '4px',
            cursor: 'pointer',
            fontSize: '0.875rem',
            marginLeft: '0.5rem',
          }}
          title="Сбросить масштаб"
        >
          100%
        </button>
      </div>

      {/* Preview content with zoom and drag to pan */}
      <div
        ref={scrollContainerRef}
        className="document-preview-container"
        style={{
          background: '#525659',
          padding: '20px',
          flex: 1,
          overflow: 'auto',
          position: 'relative',
          cursor: isDragging && hasMoved ? 'grabbing' : 'default',
        }}
        onMouseDown={(e) => {
          if (e.button === 0) { // Left mouse button
            setIsDragging(true);
            setHasMoved(false);
            setDragStart({ x: e.clientX, y: e.clientY });
            if (scrollContainerRef.current) {
              setScrollPosition({
                left: scrollContainerRef.current.scrollLeft,
                top: scrollContainerRef.current.scrollTop,
              });
            }
          }
        }}
        onMouseMove={(e) => {
          if (isDragging) {
            const deltaX = Math.abs(dragStart.x - e.clientX);
            const deltaY = Math.abs(dragStart.y - e.clientY);
            
            // Only start dragging if mouse moved more than 5px
            if (deltaX > 5 || deltaY > 5) {
              setHasMoved(true);
              if (scrollContainerRef.current) {
                e.preventDefault();
                const scrollDeltaX = dragStart.x - e.clientX;
                const scrollDeltaY = dragStart.y - e.clientY;
                scrollContainerRef.current.scrollLeft = scrollPosition.left + scrollDeltaX;
                scrollContainerRef.current.scrollTop = scrollPosition.top + scrollDeltaY;
              }
            }
          }
        }}
        onMouseUp={() => {
          if (!hasMoved && scrollContainerRef.current) {
            // If didn't move, allow normal click behavior
          }
          setIsDragging(false);
          setHasMoved(false);
        }}
        onMouseLeave={() => {
          setIsDragging(false);
          setHasMoved(false);
        }}
      >
        <div
          style={{
            transform: `scale(${zoom / 100})`,
            transformOrigin: 'top left',
            width: `${100 / (zoom / 100)}%`,
            minHeight: '100%',
          }}
        >
      <div
        ref={contentRef}
        style={{ display: 'none' }}
        dangerouslySetInnerHTML={{ __html: html }}
      />
      
      {/* Title Page */}
      {titlePageHtml && (
        <div
          className="document-page"
          style={{
            width: `${210 * MM_TO_PX}px`, // A4 width in pixels
            height: `${297 * MM_TO_PX}px`, // A4 height in pixels
            margin: '0 auto',
            background: 'white',
            boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
            pageBreakAfter: 'always',
            pageBreakInside: 'avoid',
            position: 'relative',
            overflow: 'hidden',
          }}
          onClick={onClick}
        >
          <div
            style={{
              width: '210mm',
              height: '297mm',
              position: 'relative',
              fontFamily: "'Times New Roman', Times, serif",
              margin: 0,
              padding: 0,
            }}
            dangerouslySetInnerHTML={{ __html: titlePageHtml }}
          />
        </div>
      )}

      {/* Document Pages */}
      {pages.map((pageHtml, index) => {
        const pageNumber = titlePageHtml ? index + 2 : index + 1; // Adjust page numbers if title page exists
        const adjustedTotalPages = titlePageHtml ? totalPages + 1 : totalPages;
        const headerContent = hasPageNumbers && pageNumbers?.position === 'top';
        const footerContent = hasPageNumbers && pageNumbers?.position === 'bottom';
        
        return (
          <div
            key={index}
            className="document-page"
            style={{
              width: dimensions.pageWidth,
              height: dimensions.pageHeight,
              margin: (index > 0 || titlePageHtml) ? '20px auto 0' : '0 auto',
              background: 'white',
              boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
              pageBreakAfter: 'always',
              pageBreakInside: 'avoid',
              position: 'relative',
            }}
            onClick={onClick}
          >
            {/* Header with page number - absolutely positioned at top */}
            {headerContent && (
              <div
                style={{
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  right: 0,
                  padding: `${dimensions.marginTop}px 0 0 0`,
                  width: '100%',
                  zIndex: 1,
                }}
                dangerouslySetInnerHTML={{ __html: renderPageNumber(pageNumber, adjustedTotalPages, pageNumbers, 'top') }}
              />
            )}

            {/* Content area */}
            <div
              className="document-preview"
              style={{
                width: '100%',
                height: '100%',
                padding: headerContent && footerContent
                  ? `${dimensions.marginTop + headerContentHeight}px ${dimensions.marginRight}px ${dimensions.marginBottom}px ${dimensions.marginLeft}px`
                  : headerContent
                  ? `${dimensions.marginTop + headerContentHeight}px ${dimensions.marginRight}px ${dimensions.marginBottom}px ${dimensions.marginLeft}px`
                  : footerContent
                  ? `${dimensions.marginTop}px ${dimensions.marginRight}px ${dimensions.marginBottom}px ${dimensions.marginLeft}px`
                  : `${dimensions.marginTop}px ${dimensions.marginRight}px ${dimensions.marginBottom}px ${dimensions.marginLeft}px`,
                fontFamily: "'Times New Roman', Times, serif",
                fontSize: '14pt',
                lineHeight: 1.5,
                color: '#1a1a1a',
                overflow: 'auto',
                boxSizing: 'border-box',
              }}
            >
              <div 
                dangerouslySetInnerHTML={{ __html: pageHtml }}
                style={{
                  pageBreakInside: 'avoid',
                }}
              />
            </div>

            {/* Footer with page number - absolutely positioned at bottom with strict marginBottom */}
            {footerContent && (
              <div
                style={{
                  position: 'absolute',
                  bottom: 0,
                  left: 0,
                  right: 0,
                  height: `${dimensions.marginBottom}px`,
                  width: '100%',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'flex-end',
                  zIndex: 1,
                }}
                dangerouslySetInnerHTML={{ __html: renderPageNumber(pageNumber, adjustedTotalPages, pageNumbers, 'bottom') }}
              />
            )}
          </div>
        );
      })}
        </div>
      </div>
    </div>
  );
}

// frontend/src/widgets/document-preview/DocumentPreview.vue
<template>
	<div class="document-preview">
		<div v-if="isLoading" class="document-preview__loading">Загрузка...</div>
		<div v-else ref="previewContainerRef" class="document-preview__container">
			<!-- Title Page -->
			<div
				v-if="titlePageHtml"
				class="document-preview__page-wrapper"
			>
				<div
					class="document-preview__page document-preview__page--title"
					:style="getTitlePageStyle()"
				>
					<div
						class="document-preview__title-page-content"
						v-html="titlePageHtml"
					/>
				</div>
			</div>

			<!-- Document Pages -->
			<div
				v-for="(page, index) in pages"
				:key="index"
				class="document-preview__page-wrapper"
			>
				<div
					class="document-preview__page"
					:style="getPageStyle(index, titlePageHtml ? 1 : 0)"
				>
				<!-- Header with page number - absolutely positioned at top -->
				<div
					v-if="showHeader"
					class="document-preview__header"
					:style="getHeaderStyle()"
					v-html="renderPageNumber(getPageNumber(index), totalPages)"
				/>

				<!-- Content area -->
				<div
					class="document-preview__content"
					:style="getContentStyle(showHeader)"
					v-html="page"
				/>

				<!-- Footer with page number - absolutely positioned at bottom -->
				<div
					v-if="showFooter"
					class="document-preview__footer"
					:style="getFooterStyle()"
					v-html="renderPageNumber(getPageNumber(index), totalPages)"
				/>
				</div>
			</div>
		</div>
	</div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, nextTick } from 'vue';
import { useElementSize } from '@vueuse/core';
import ProfileAPI from '@/entities/profile/api/ProfileAPI';
import TitlePageAPI from '@/entities/title-page/api/TitlePageAPI';
import { renderDocument } from '@/utils/documentRenderer';
import { renderTitlePageToHtml } from '@/utils/titlePageRenderer';
import { splitIntoPages } from '@/utils/pageUtils';
import {
	calculatePageDimensions,
	type PageDimensions,
} from '@/utils/pageConstants';
import type { ProfileData } from '@/entities/profile/types';
import type { TitlePageWithData } from '@/entities/title-page/api/TitlePageAPI';
import 'katex/dist/katex.css';

interface Props {
	content: string;
	profileId?: string;
	titlePageId?: string;
	variables?: Record<string, string>;
	documentId: string;
}

const props = defineProps<Props>();

const previewContainerRef = ref<HTMLElement | null>(null);
const { width: containerWidth } = useElementSize(previewContainerRef);

const profileData = ref<ProfileData | null>(null);
const titlePage = ref<TitlePageWithData | null>(null);
const titlePageHtml = ref<string>('');
const pages = ref<string[]>([]);
const isLoading = ref(false);
const isUpdatingPages = ref(false);
const isLoadingTitlePage = ref(false);

// Calculate page dimensions reactively based on profile
const dimensions = computed<PageDimensions>(() => {
	return calculatePageDimensions(profileData.value);
});

// Calculate available content height (accounting for margins and header/footer)
const headerContentHeight = computed(() => {
	const pageNumbers = profileData.value?.pageSettings?.pageNumbers;
	if (!pageNumbers?.enabled || pageNumbers.position !== 'top') {
		return 0;
	}
	// Approximate height for page number header
	return (pageNumbers.fontSize || 12) * 1.2; // fontSize * lineHeight
});

const contentHeight = computed(() => {
	return (
		dimensions.value.pageHeight -
		dimensions.value.marginTop -
		dimensions.value.marginBottom -
		headerContentHeight.value
	);
});

const contentWidth = computed(() => {
	return (
		dimensions.value.pageWidth -
		dimensions.value.marginLeft -
		dimensions.value.marginRight
	);
});

const showHeader = computed(() => {
	const pageNumbers = profileData.value?.pageSettings.pageNumbers;
	return pageNumbers?.enabled && pageNumbers.position === 'top';
});

const showFooter = computed(() => {
	const pageNumbers = profileData.value?.pageSettings.pageNumbers;
	return pageNumbers?.enabled && pageNumbers.position === 'bottom';
});

/**
 * Render page number based on settings
 * Pure function - no side effects
 */
function renderPageNumber(
	pageNumber: number,
	totalPagesCount: number
): string {
	const pageNumbers = profileData.value?.pageSettings.pageNumbers;
	if (!pageNumbers?.enabled) {
		return '';
	}

	const format = (pageNumbers.format || '{n}')
		.replace('{n}', String(pageNumber))
		.replace('{total}', String(totalPagesCount));

	const fontSize = pageNumbers.fontSize || 12;
	const fontFamily = pageNumbers.fontFamily
		? `font-family: ${pageNumbers.fontFamily};`
		: '';
	const fontStyle = pageNumbers.fontStyle
		? `font-style: ${pageNumbers.fontStyle};`
		: '';
	const textAlign = `text-align: ${pageNumbers.align || 'center'};`;

	return `
		<div style="${fontFamily} ${fontStyle} font-size: ${fontSize}pt; ${textAlign} width: 100%; color: #000;">
			${format}
		</div>
	`;
}

/**
 * Load and render title page
 */
async function loadTitlePage() {
	if (!props.titlePageId) {
		titlePage.value = null;
		titlePageHtml.value = '';
		return;
	}

	isLoadingTitlePage.value = true;
	try {
		const loadedTitlePage = await TitlePageAPI.getById(props.titlePageId);
		titlePage.value = loadedTitlePage;
		
		const variables = props.variables || {};
		titlePageHtml.value = renderTitlePageToHtml(loadedTitlePage, variables);
	} catch (error) {
		console.error('Failed to load title page:', error);
		titlePage.value = null;
		titlePageHtml.value = '';
	} finally {
		isLoadingTitlePage.value = false;
	}
}

const totalPages = computed(() => {
	return pages.value.length + (titlePageHtml.value ? 1 : 0);
});

const getPageNumber = (index: number): number => {
	return index + 1 + (titlePageHtml.value ? 1 : 0);
};

// Calculate scale factor to fit container width
const scaleFactor = computed(() => {
	if (!containerWidth.value || !dimensions.value.pageWidth) return 1;
	// Account for padding on both sides (spacing-lg typically 16px each side = 32px total)
	const padding = 32; 
	const availableWidth = Math.max(200, containerWidth.value - padding);
	const scale = availableWidth / dimensions.value.pageWidth;
	// Ensure scale never exceeds 1 and is at least 0.2 for readability
	return Math.min(1, Math.max(0.2, scale));
});

/**
 * Get title page style
 */
function getTitlePageStyle() {
	const MM_TO_PX = 3.7795275591;
	const A4_WIDTH_MM = 210;
	const A4_HEIGHT_MM = 297;
	const A4_WIDTH_PX = A4_WIDTH_MM * MM_TO_PX;
	const A4_HEIGHT_PX = A4_HEIGHT_MM * MM_TO_PX;
	
	const scale = scaleFactor.value;
	const scaledWidth = A4_WIDTH_PX * scale;
	
	return {
		width: `${A4_WIDTH_PX}px`,
		height: `${A4_HEIGHT_PX}px`,
		margin: '0 auto',
		background: 'white',
		boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
		pageBreakAfter: 'always' as const,
		pageBreakInside: 'avoid' as const,
		position: 'relative' as const,
		overflow: 'hidden' as const,
		transform: `scale(${scale})`,
		transformOrigin: 'top center',
		marginBottom: `${20 * scale}px`, // Use scaled margin between pages
		maxWidth: `${scaledWidth}px`,
		minWidth: `${scaledWidth}px`,
	};
}

/**
 * Get page style computed property
 */
function getPageStyle(index: number, offset: number = 0) {
	const scale = scaleFactor.value;
	const baseMarginTop = (index + offset) > 0 ? 20 : 0;
	const scaledWidth = dimensions.value.pageWidth * scale;
	
	return {
		width: `${dimensions.value.pageWidth}px`,
		height: `${dimensions.value.pageHeight}px`,
		margin: `${baseMarginTop}px auto 0`,
		background: 'white',
		boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
		pageBreakAfter: 'always' as const,
		pageBreakInside: 'avoid' as const,
		position: 'relative' as const,
		overflow: 'hidden' as const,
		transform: `scale(${scale})`,
		transformOrigin: 'top center',
		marginBottom: `${20 * scale}px`, // Use scaled margin between pages
		maxWidth: `${scaledWidth}px`,
		minWidth: `${scaledWidth}px`,
	};
}

/**
 * Get header style computed property
 */
function getHeaderStyle() {
	return {
		position: 'absolute' as const,
		top: '0',
		left: '0',
		right: '0',
		padding: `${dimensions.value.marginTop}px 0 0 0`,
		width: '100%',
		zIndex: 1,
	};
}

/**
 * Get content style computed property
 */
function getContentStyle(hasHeader: boolean = false) {
	const paddingTop = hasHeader
		? dimensions.value.marginTop + headerContentHeight.value
		: dimensions.value.marginTop;

	return {
		width: '100%',
		height: '100%',
		padding: `${paddingTop}px ${dimensions.value.marginRight}px ${dimensions.value.marginBottom}px ${dimensions.value.marginLeft}px`,
		fontFamily: "'Times New Roman', Times, serif",
		fontSize: '14pt',
		lineHeight: 1.5,
		color: '#1a1a1a',
		boxSizing: 'border-box' as const,
		pageBreakInside: 'avoid' as const,
	};
}

/**
 * Get footer style computed property
 */
function getFooterStyle() {
	return {
		position: 'absolute' as const,
		bottom: '0',
		left: '0',
		right: '0',
		height: `${dimensions.value.marginBottom}px`,
		width: '100%',
		display: 'flex' as const,
		flexDirection: 'column' as const,
		justifyContent: 'flex-end' as const,
		zIndex: 1,
	};
}

/**
 * Generate rendered HTML from markdown with profile styles
 */
async function generateRenderedHTML(): Promise<string> {
	if (!props.content.trim()) {
		return '';
	}

	// Load profile if needed
	if (props.profileId && !profileData.value) {
		try {
			const profile = await ProfileAPI.getById(props.profileId);
			if (profile.data) {
				profileData.value = profile.data;
			}
		} catch (error) {
			console.error('Failed to load profile:', error);
		}
	}

	// Render markdown with profile styles
	const renderedHtml = renderDocument({
		markdown: props.content,
		profile: profileData.value,
		overrides: {},
		selectable: false,
	});
	return renderedHtml;
}

/**
 * Update pages reactively
 */
async function updatePages() {
	if (!props.content.trim()) {
		pages.value = [];
		isUpdatingPages.value = false;
		return;
	}

	isUpdatingPages.value = true;

	try {
		// Generate rendered HTML
		const renderedHtml = await generateRenderedHTML();

		if (!renderedHtml) {
			pages.value = [];
			return;
		}

		// Split into pages asynchronously using requestIdleCallback if available
		const scheduleSplit = (callback: () => void) => {
			if (typeof requestIdleCallback !== 'undefined') {
				requestIdleCallback(callback, { timeout: 1000 });
			} else {
				setTimeout(callback, 0);
			}
		};

		scheduleSplit(() => {
			try {
				const splitPages = splitIntoPages(
					renderedHtml,
					contentHeight.value,
					contentWidth.value
				);
				pages.value = splitPages;
				nextTick(() => {
					handleImageLoading();
				});
			} catch (error) {
				console.error('Failed to split pages:', error);
				pages.value = [renderedHtml];
				nextTick(() => {
					handleImageLoading();
				});
			} finally {
				isUpdatingPages.value = false;
			}
		});
	} catch (error) {
		console.error('Failed to update pages:', error);
		pages.value = [];
		isUpdatingPages.value = false;
	}
}

let handleImageLoadingTimeout: ReturnType<typeof setTimeout> | null = null;

/**
 * Handle image loading errors and add loading states
 */
function handleImageLoading() {
	// Debounce to prevent multiple rapid calls
	if (handleImageLoadingTimeout) {
		clearTimeout(handleImageLoadingTimeout);
	}
	
	handleImageLoadingTimeout = setTimeout(() => {
		const contentElements = document.querySelectorAll('.document-preview__content');
		contentElements.forEach((contentEl) => {
		const images = contentEl.querySelectorAll('img');
		images.forEach((img) => {
			// Skip if already processed
			if (img.dataset.processed === 'true') {
				return;
			}
			
			img.dataset.processed = 'true';
			
			// Check if image is already loaded (from cache or previous load)
			if (img.complete && img.naturalWidth > 0) {
				// Image already loaded, show it immediately
				img.style.opacity = '1';
				return;
			}
			
			// Add loading state only if image is not already loaded
			img.style.opacity = '0';
			img.style.transition = 'opacity 0.3s ease';
			
			// Handle successful load
			img.onload = () => {
				img.style.opacity = '1';
			};
			
			// Handle load error
			img.onerror = (event) => {
				console.error('Failed to load image:', img.src, event);
				
				// Prevent infinite retry loops
				const retryCount = parseInt(img.dataset.retryCount || '0');
				if (retryCount >= 2) {
					// Max retries reached, show error styling
					img.style.opacity = '1';
					img.style.border = '2px dashed #ff4444';
					img.style.padding = '10px';
					img.style.backgroundColor = '#ffeeee';
					return;
				}
				
				img.dataset.retryCount = String(retryCount + 1);
				img.style.opacity = '1';
				
				// Try to reload with fresh token if current one failed
				try {
					const currentToken = getCurrentAuthToken();
					if (currentToken && img.src) {
						let url: URL;
						try {
							// Try to parse URL - handle both absolute and relative
							if (img.src.startsWith('http://') || img.src.startsWith('https://')) {
								url = new URL(img.src);
							} else {
								url = new URL(img.src, window.location.origin);
							}
						} catch (parseError) {
							// If URL parsing fails, try to fix it manually
							// Remove any malformed query parameters and rebuild
							const baseUrl = img.src.split('?')[0].split('&')[0];
							url = new URL(baseUrl, window.location.origin);
						}
						
						// Always update token to ensure it's fresh
						url.searchParams.set('token', currentToken);
						const newSrc = url.toString();
						
						// Remove error handlers temporarily to avoid recursion
						const oldOnError = img.onerror;
						img.onerror = null;
						
						// Use a small delay to ensure previous request is cancelled
						setTimeout(() => {
							img.src = newSrc;
							// Restore error handler after image starts loading
							setTimeout(() => {
								if (!img.complete && !img.naturalWidth) {
									img.onerror = oldOnError;
								}
							}, 50);
						}, 100);
						return;
					}
				} catch (urlError) {
					console.error('Failed to parse image URL:', urlError);
				}
				
				// Add error styling only if reload didn't help
				img.style.border = '2px dashed #ff4444';
				img.style.padding = '10px';
				img.style.backgroundColor = '#ffeeee';
			};
		});
		});
	}, 100); // Debounce delay
}

/**
 * Get current auth token from localStorage
 */
function getCurrentAuthToken(): string | null {
	try {
		const authData = localStorage.getItem('auth-storage');
		if (authData) {
			const parsed = JSON.parse(authData);
			return parsed?.state?.accessToken || parsed?.accessToken || null;
		}
	} catch (error) {
		console.error('Failed to get auth token:', error);
	}
	return null;
}

// Load profile when profileId changes
watch(
	() => props.profileId,
	async (newProfileId, oldProfileId) => {
		if (newProfileId === oldProfileId) return;
		
		if (newProfileId) {
			isLoading.value = true;
			try {
				const profile = await ProfileAPI.getById(newProfileId);
				if (profile.data) {
					profileData.value = profile.data;
				}
			} catch (error) {
				console.error('Failed to load profile:', error);
				profileData.value = null;
			} finally {
				isLoading.value = false;
			}
		} else {
			profileData.value = null;
		}
	},
	{ immediate: true }
);

// Load title page when titlePageId or variables change
watch(
	[() => props.titlePageId, () => props.variables],
	async () => {
		await loadTitlePage();
	},
	{ immediate: true, deep: true }
);

// Update pages when content or profile changes
watch(
	[() => props.content, () => profileData.value],
	() => {
		updatePages();
	},
	{ immediate: false } // Don't run immediately, wait for profile to load first
);

onMounted(async () => {
	// Load profile first if needed
	if (props.profileId) {
		try {
			const profile = await ProfileAPI.getById(props.profileId);
			if (profile.data) {
				profileData.value = profile.data;
			}
		} catch (error) {
			console.error('Failed to load profile:', error);
		}
	}
	
	// Load title page if needed
	await loadTitlePage();
	
	// Then update pages
	await updatePages();
	
	// Handle images after initial render
	nextTick(() => {
		handleImageLoading();
	});
});
</script>

<style scoped>
.document-preview {
	height: 100%;
	display: flex;
	flex-direction: column;
	background: var(--bg-tertiary);
	padding: var(--spacing-lg);
}

.document-preview__loading {
	display: flex;
	align-items: center;
	justify-content: center;
	height: 100%;
	color: var(--text-secondary);
}

.document-preview__container {
	flex: 1;
	display: flex;
	flex-direction: column;
	align-items: center;
	overflow-y: auto;
	overflow-x: auto;
	padding: var(--spacing-lg);
	min-width: 0;
	width: 100%;
	box-sizing: border-box;
}

.document-preview__page-wrapper {
	flex-shrink: 0;
	width: 100%;
	max-width: 100%;
	display: flex;
	justify-content: center;
	align-items: flex-start;
	overflow: visible;
	min-width: 0;
	padding: 0;
	margin: 0;
}

.document-preview__page {
	flex-shrink: 0;
	box-sizing: border-box;
	overflow: visible;
}

.document-preview__header,
.document-preview__footer {
	/* Styles applied via inline styles */
	position: relative;
}

.document-preview__content {
	/* Styles applied via inline styles */
	overflow: visible;
}

.document-preview__title-page-content {
	width: 210mm;
	height: 297mm;
	position: relative;
	font-family: 'Times New Roman', Times, serif;
	margin: 0;
	padding: 0;
}

.document-preview__content :deep(*) {
	page-break-inside: avoid;
}

.document-preview__content :deep(p),
.document-preview__content :deep(h1),
.document-preview__content :deep(h2),
.document-preview__content :deep(h3),
.document-preview__content :deep(h4),
.document-preview__content :deep(h5),
.document-preview__content :deep(h6),
.document-preview__content :deep(ul),
.document-preview__content :deep(ol),
.document-preview__content :deep(li),
.document-preview__content :deep(table),
.document-preview__content :deep(blockquote),
.document-preview__content :deep(pre) {
	page-break-inside: avoid;
}
</style>
