// client/src/presentation/components/ElementEditor.tsx
import { useState, useEffect } from 'react';
import type { TitlePageElement } from '../../../../shared/src/types';
import { FONT_FAMILIES } from '../../../../shared/src/types';

interface ElementEditorProps {
  element: TitlePageElement | null;
  onUpdate: (element: TitlePageElement) => void;
  onDelete: () => void;
}

export function ElementEditor({ element, onUpdate, onDelete }: ElementEditorProps) {
  const [localElement, setLocalElement] = useState<TitlePageElement | null>(element);

  useEffect(() => {
    setLocalElement(element);
  }, [element]);

  if (!localElement) {
    return (
      <div style={{ padding: '1rem', border: '1px solid #ddd', borderRadius: '4px' }}>
        <p style={{ color: '#666' }}>Выберите элемент для редактирования</p>
      </div>
    );
  }

  const handleChange = (updates: Partial<TitlePageElement>) => {
    const updated = { ...localElement, ...updates };
    setLocalElement(updated);
    onUpdate(updated);
  };

  return (
    <div style={{ padding: '1rem', border: '1px solid #ddd', borderRadius: '4px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: 600 }}>
          {localElement.type === 'text' && 'Текст'}
          {localElement.type === 'variable' && 'Переменная'}
          {localElement.type === 'line' && 'Линия'}
        </h3>
        <button
          onClick={onDelete}
          style={{
            padding: '0.25rem 0.5rem',
            background: '#dc3545',
            color: '#fff',
            border: 'none',
            borderRadius: '4px',
            cursor: 'pointer',
            fontSize: '0.875rem',
          }}
        >
          Удалить
        </button>
      </div>

      {/* Position */}
      <div style={{ marginBottom: '1rem' }}>
        <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Позиция (мм)</label>
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <input
            type="number"
            value={localElement.x}
            onChange={(e) => handleChange({ x: parseFloat(e.target.value) || 0 })}
            style={{ width: '100px', padding: '0.25rem' }}
            placeholder="X"
          />
          <input
            type="number"
            value={localElement.y}
            onChange={(e) => handleChange({ y: parseFloat(e.target.value) || 0 })}
            style={{ width: '100px', padding: '0.25rem' }}
            placeholder="Y"
          />
        </div>
      </div>

      {/* Text/Variable specific */}
      {(localElement.type === 'text' || localElement.type === 'variable') && (
        <>
          {localElement.type === 'text' && (
            <div style={{ marginBottom: '1rem' }}>
              <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Текст</label>
              <textarea
                value={localElement.content || ''}
                onChange={(e) => handleChange({ content: e.target.value })}
                style={{ width: '100%', padding: '0.25rem', minHeight: '60px' }}
                placeholder="Введите текст"
              />
            </div>
          )}

          {localElement.type === 'variable' && (
            <div style={{ marginBottom: '1rem' }}>
              <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Ключ переменной</label>
              <input
                type="text"
                value={localElement.variableKey || ''}
                onChange={(e) => handleChange({ variableKey: e.target.value })}
                style={{ width: '100%', padding: '0.25rem' }}
                placeholder="например: university"
              />
            </div>
          )}

          <div style={{ marginBottom: '1rem' }}>
            <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Размер шрифта (pt)</label>
            <input
              type="number"
              value={localElement.fontSize || 14}
              onChange={(e) => handleChange({ fontSize: parseFloat(e.target.value) || 14 })}
              style={{ width: '100%', padding: '0.25rem' }}
              min="8"
              max="72"
            />
          </div>

          <div style={{ marginBottom: '1rem' }}>
            <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Шрифт</label>
            <select
              value={localElement.fontFamily || ''}
              onChange={(e) => handleChange({ fontFamily: e.target.value })}
              style={{ width: '100%', padding: '0.25rem' }}
            >
              {FONT_FAMILIES.map((font) => (
                <option key={font.value} value={font.value}>
                  {font.label}
                </option>
              ))}
            </select>
          </div>

          <div style={{ marginBottom: '1rem' }}>
            <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Начертание</label>
            <select
              value={localElement.fontWeight || 'normal'}
              onChange={(e) => handleChange({ fontWeight: e.target.value as 'normal' | 'bold' })}
              style={{ width: '100%', padding: '0.25rem' }}
            >
              <option value="normal">Обычный</option>
              <option value="bold">Жирный</option>
            </select>
          </div>

          <div style={{ marginBottom: '1rem' }}>
            <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Стиль</label>
            <select
              value={localElement.fontStyle || 'normal'}
              onChange={(e) => handleChange({ fontStyle: e.target.value as 'normal' | 'italic' })}
              style={{ width: '100%', padding: '0.25rem' }}
            >
              <option value="normal">Обычный</option>
              <option value="italic">Курсив</option>
            </select>
          </div>

          <div style={{ marginBottom: '1rem' }}>
            <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Междустрочный интервал</label>
            <input
              type="number"
              value={localElement.lineHeight || 1.2}
              onChange={(e) => handleChange({ lineHeight: parseFloat(e.target.value) || 1.2 })}
              style={{ width: '100%', padding: '0.25rem' }}
              min="0.5"
              max="3"
              step="0.1"
            />
            <small style={{ color: '#666', fontSize: '0.75rem' }}>Множитель (например, 1.2 = 120%)</small>
          </div>

          <div style={{ marginBottom: '1rem' }}>
            <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Выравнивание</label>
            <select
              value={localElement.textAlign || 'left'}
              onChange={(e) => handleChange({ textAlign: e.target.value as 'left' | 'center' | 'right' })}
              style={{ width: '100%', padding: '0.25rem' }}
            >
              <option value="left">Слева</option>
              <option value="center">По центру</option>
              <option value="right">Справа</option>
            </select>
          </div>
        </>
      )}

      {/* Line specific */}
      {localElement.type === 'line' && (
        <>
          <div style={{ marginBottom: '1rem' }}>
            <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Длина (мм)</label>
            <input
              type="number"
              value={localElement.length || 100}
              onChange={(e) => handleChange({ length: parseFloat(e.target.value) || 100 })}
              style={{ width: '100%', padding: '0.25rem' }}
              min="1"
            />
          </div>

          <div style={{ marginBottom: '1rem' }}>
            <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.875rem' }}>Толщина (мм)</label>
            <input
              type="number"
              value={localElement.thickness || 1}
              onChange={(e) => handleChange({ thickness: parseFloat(e.target.value) || 1 })}
              style={{ width: '100%', padding: '0.25rem' }}
              min="0.1"
              step="0.1"
            />
          </div>
        </>
      )}
    </div>
  );
}

// frontend/src/widgets/title-page/ElementEditor.vue
<template>
	<div class="element-editor">
		<div
			v-if="!element"
			class="empty-state"
		>
			<p>Выберите элемент для редактирования</p>
		</div>

		<div
			v-else
			class="editor-content"
		>
			<div class="header">
				<h3>{{ elementTypeLabel }}</h3>
				<button
					class="delete-btn"
					@click="handleDelete"
				>
					Удалить
				</button>
			</div>

			<!-- Position -->
			<div class="field">
				<label>Позиция (мм)</label>
				<div class="position-inputs">
					<input
						v-model.number="localX"
						type="number"
						step="0.1"
						placeholder="X"
						@blur="handlePositionBlur('x')"
					/>
					<input
						v-model.number="localY"
						type="number"
						step="0.1"
						placeholder="Y"
						@blur="handlePositionBlur('y')"
					/>
				</div>
			</div>

			<!-- Text/Variable specific -->
			<template v-if="element.type === 'text' || element.type === 'variable'">
				<div
					v-if="element.type === 'text'"
					class="field"
				>
					<label>Текст</label>
					<textarea
						v-model="localContent"
						placeholder="Введите текст"
						@input="handleChange({ content: localContent })"
					/>
				</div>

				<div
					v-if="element.type === 'variable'"
					class="field"
				>
					<label>Ключ переменной</label>
					<input
						v-model="localVariableKey"
						type="text"
						placeholder="например: university"
						@input="handleChange({ variableKey: localVariableKey })"
					/>
				</div>

				<div class="field">
					<label>Размер шрифта (pt)</label>
					<input
						v-model.number="localFontSize"
						type="number"
						min="8"
						max="72"
						@input="handleChange({ fontSize: localFontSize || 14 })"
						@blur="handleNumericBlur('fontSize', 14)"
					/>
				</div>

				<div class="field">
					<label>Шрифт</label>
					<select
						v-model="localFontFamily"
						@change="handleChange({ fontFamily: localFontFamily })"
					>
						<option value="">По умолчанию</option>
						<option
							v-for="font in FONT_FAMILIES"
							:key="font.value"
							:value="font.value"
						>
							{{ font.label }}
						</option>
					</select>
				</div>

				<div class="field">
					<label>Начертание</label>
					<select
						v-model="localFontWeight"
						@change="handleChange({ fontWeight: localFontWeight })"
					>
						<option value="normal">Обычный</option>
						<option value="bold">Жирный</option>
					</select>
				</div>

				<div class="field">
					<label>Стиль</label>
					<select
						v-model="localFontStyle"
						@change="handleChange({ fontStyle: localFontStyle })"
					>
						<option value="normal">Обычный</option>
						<option value="italic">Курсив</option>
					</select>
				</div>

				<div class="field">
					<label>Междустрочный интервал</label>
					<input
						v-model.number="localLineHeight"
						type="number"
						min="0.5"
						max="3"
						step="0.1"
						@input="handleChange({ lineHeight: localLineHeight || 1.2 })"
						@blur="handleNumericBlur('lineHeight', 1.2)"
					/>
					<small>Множитель (например, 1.2 = 120%)</small>
				</div>

				<div class="field">
					<label>Выравнивание</label>
					<select
						v-model="localTextAlign"
						@change="handleChange({ textAlign: localTextAlign })"
					>
						<option value="left">Слева</option>
						<option value="center">По центру</option>
						<option value="right">Справа</option>
					</select>
				</div>
			</template>

			<!-- Line specific -->
			<template v-if="element.type === 'line'">
				<div class="field">
					<label>Длина (мм)</label>
					<input
						v-model.number="localLength"
						type="number"
						min="1"
						@input="handleChange({ length: localLength || 100 })"
						@blur="handleNumericBlur('length', 100)"
					/>
				</div>

				<div class="field">
					<label>Толщина (мм)</label>
					<input
						v-model.number="localThickness"
						type="number"
						min="0.1"
						step="0.1"
						@input="handleChange({ thickness: localThickness || 1 })"
						@blur="handleNumericBlur('thickness', 1)"
					/>
				</div>
			</template>
		</div>
	</div>
</template>

<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import type { TitlePageElement } from '@/shared/types/titlePage';
import { FONT_FAMILIES } from '@/entities/profile/constants';

interface Props {
	element: TitlePageElement | null;
}

interface Emits {
	(e: 'update', element: TitlePageElement): void;
	(e: 'delete'): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const elementTypeLabel = computed(() => {
	if (!props.element) return '';
	if (props.element.type === 'text') return 'Текст';
	if (props.element.type === 'variable') return 'Переменная';
	if (props.element.type === 'line') return 'Линия';
	return '';
});

const localX = ref(0);
const localY = ref(0);
const localContent = ref('');
const localVariableKey = ref('');
const localFontSize = ref(14);
const localFontFamily = ref('');
const localFontWeight = ref<'normal' | 'bold'>('normal');
const localFontStyle = ref<'normal' | 'italic'>('normal');
const localLineHeight = ref(1.2);
const localTextAlign = ref<'left' | 'center' | 'right'>('left');
const localLength = ref(100);
const localThickness = ref(1);

function syncFromElement() {
	if (!props.element) return;

	localX.value = props.element.x ?? 0;
	localY.value = props.element.y ?? 0;
	localContent.value = props.element.content || '';
	localVariableKey.value = props.element.variableKey || '';
	localFontSize.value = props.element.fontSize ?? 14;
	localFontFamily.value = props.element.fontFamily || '';
	localFontWeight.value = props.element.fontWeight || 'normal';
	localFontStyle.value = props.element.fontStyle || 'normal';
	localLineHeight.value = props.element.lineHeight ?? 1.2;
	localTextAlign.value = props.element.textAlign || 'left';
	localLength.value = props.element.length ?? 100;
	localThickness.value = props.element.thickness ?? 1;
}

watch(
	() => props.element,
	() => {
		syncFromElement();
	},
	{ immediate: true, deep: true }
);

function handleChange(updates: Partial<TitlePageElement>) {
	if (!props.element) return;
	const updated = { ...props.element, ...updates };
	emit('update', updated);
}

function handlePositionBlur(field: 'x' | 'y') {
	if (!props.element) return;
	const value = field === 'x' ? localX.value : localY.value;
	const rounded = parseFloat(value.toFixed(1));
	handleChange({ [field]: rounded });
}

function handleNumericBlur(
	field: 'fontSize' | 'lineHeight' | 'length' | 'thickness',
	defaultValue: number
) {
	if (!props.element) return;
	const value =
		field === 'fontSize'
			? localFontSize.value
			: field === 'lineHeight'
				? localLineHeight.value
				: field === 'length'
					? localLength.value
					: localThickness.value;

	if (isNaN(value) || value === undefined || value === null) {
		handleChange({ [field]: defaultValue });
	} else {
		handleChange({ [field]: value });
	}
}

function handleDelete() {
	emit('delete');
}
</script>

<style scoped>
.element-editor {
	padding: 1rem;
	border: 1px solid #ddd;
	border-radius: 4px;
}

.empty-state {
	color: #666;
}

.editor-content {
	display: flex;
	flex-direction: column;
	gap: 1rem;
}

.header {
	display: flex;
	justify-content: space-between;
	align-items: center;
	margin-bottom: 1rem;
}

.header h3 {
	margin: 0;
	font-size: 1rem;
	font-weight: 600;
}

.delete-btn {
	padding: 0.25rem 0.5rem;
	background: #dc3545;
	color: #fff;
	border: none;
	border-radius: 4px;
	cursor: pointer;
	font-size: 0.875rem;
}

.field {
	display: flex;
	flex-direction: column;
	gap: 0.25rem;
}

.field label {
	font-size: 0.875rem;
}

.field input,
.field textarea,
.field select {
	padding: 0.25rem;
	width: 100%;
}

.field textarea {
	min-height: 60px;
}

.position-inputs {
	display: flex;
	gap: 0.5rem;
}

.position-inputs input {
	width: 100px;
}

.field small {
	color: #666;
	font-size: 0.75rem;
}
</style>
